***

layout: page
permalink: /publications/
title: Publications
description: publications by categories in reversed chronological order. generated by jekyll-scholar.
nav: true
nav\_order: 2
-------------

{% include bib\_search.liquid %}

{% bibliography %}
